### ISSUE TITLE
Validation issue in booking appoitment

### ISSUE THREAD

**Issue by PrasuHirapara** [yazdanhaider/Hospital-Management#11]
![image](https://github.com/user-attachments/assets/12e0a47b-4be4-41b6-98c0-91a2e0759efe)
Form validation is not proper. User should must be validated before submitting the form. **Number are not valid in username.**

**Comment by PrasuHirapara** [comment]
i would like to solve this issue under hacktoberfest contribution.

**Comment by yazdanhaider** [comment]
Go ahead and work on this issue @PrasuHirapara. Please ensure proper form validation, especially for the Patient name (no numbers allowed). Additionally, if possible, add a feature to allow users to download their booked appointment details in PDF format.

**Comment by PrasuHirapara** [comment]
Sure i will do the task.
