### ISSUE TITLE
Improve Background and Footer Design

### ISSUE THREAD

**Issue by Harithaa2004** [yazdanhaider/Hospital-Management#12]
The current background and footer of the project could benefit from enhancements to improve the visual appeal and user experience. Suggested improvements:

1.Update the background to a more modern design.

2.Enhance the footer to include important links such as "Contact Us", "Privacy Policy", and social media icons.

3.Ensure both the background and footer are fully responsive on all devices

kindly assign this to me under hacktober contribution

**Comment by yazdanhaider** [comment]
Hey @Harithaa2004, could you please share the background design you plan to work on? I’d like to see the concept before you proceed.

**Comment by Harithaa2004** [comment]
![image](https://github.com/user-attachments/assets/dac97cf6-1f42-4c4c-b518-e4c972f8a0e3)
How about this, if there are any changes do mention so I can design accordingly
