### ISSUE TITLE
Introduce Pasword strenth checker in SignUp page

### ISSUE THREAD

**Issue by nileshkr022** [yazdanhaider/Hospital-Management#14]
I want to integrate a password strength checker feature in SIgnUp page

**Comment by sanjaymajji** [comment]
do you wanna append this password thing with some backend peripheral or just you want it on frontend??

**Comment by sanjaymajji** [comment]
i've added password strength with a password with minimum of 8 char's and also added more checks like uppercase letters, numbers, and special characters to enhance security.

**Comment by yazdanhaider** [comment]
Heyyy @nileshkr022 and @sanjaymajji, since @nileshkr022 created the issue first, I will assign it to him. However if he’s okay with it, I can assign you both to work on this together! Let me know your thoughts.

**Comment by nileshkr022** [comment]
> Heyyy @nileshkr022 and @sanjaymajji, since @nileshkr022 created the issue first, I will assign it to him. However if he’s okay with it, I can assign you both to work on this together! Let me know your thoughts.

I'll do it myself.

**Comment by yazdanhaider** [comment]
Move ahead @nileshkr022!!

Happy Contributing!!🚀
