### ISSUE TITLE
Addition of Not Found Error Page

### ISSUE THREAD

**Issue by MoazamAli45** [yazdanhaider/Hospital-Management#19]
I will develop a Design Friendly Not Found Page. Please assign it to me

**Comment by yazdanhaider** [comment]
@MoazamAli45 Could you please specify on which page you would like to add the Design Friendly Not Found Page?

**Comment by MoazamAli45** [comment]
> @MoazamAli45 Could you please specify on which page you would like to add the Design Friendly Not Found Page?

![image](https://github.com/user-attachments/assets/2cc16b34-3870-4eb9-a339-c7e910a80afd)

Actually I want to create custom 404 page for invalid urls

**Comment by yazdanhaider** [comment]
Ok git. @MoazamAli45 Go ahead!!

**Comment by MoazamAli45** [comment]
Thank you

**Comment by nancy-gupta123** [comment]
Hello! I'd like to work on this issue. Could you please assign it to me?
