### ISSUE TITLE
[Feature]: Creating Page for Appointments

### ISSUE THREAD

**Issue by Priyanshuraj21030** [yazdanhaider/Hospital-Management#2]
I will create a page for the appointments booking which helps users to get appointed easily with the renowned doctors.

Please assign me to contribute on this project.
Also please label it to hacktoberaccepted.

**Comment by yazdanhaider** [comment]
> I will create a page for the appointments booking which helps users to get appointed easily with the renowned doctors.
> 
> Please assign me to contribute on this project. Also please label it to hacktoberaccepted.

Great go on @Priyanshuraj21030 and make sure to read the CONTRIBUTING guideline carefully.
