### ISSUE TITLE
Homepage UI enhancement

### ISSUE THREAD

**Issue by yazdanhaider** [yazdanhaider/Hospital-Management#20]
# Homepage UI Enhancement

Hey @team, I am planning to enhance the UI of the homepage to improve user experience and aesthetics. I have a design ready if anyone would like to collaborate on it. Let me know your thoughts or if you have any suggestions!

# Screenshot
![hopital managemnet homepage and footer design](https://github.com/user-attachments/assets/80163269-978f-4eb9-86d9-3856d15e3bb8)

**Comment by CemWebDev** [comment]
Hey! The design looks really clean and professional, especially the readability of the text and the headline is quite eye-catching. I have a few suggestions that could enhance the user experience:

- You might want to make the "Log in" button in the top menu a bit more prominent. For example, increasing the contrast or slightly enlarging the text size could help it stand out more.
- Adding a subtle opacity layer over the background image might make the text even easier to read.

If you'd like to discuss these improvements or collaborate, I'm happy to help.

**Comment by yazdanhaider** [comment]
Heyyyy @CemWebDev Thank you for the feedback! I’m glad you found the design clean and professional also i appreciate your suggestions for enhancing the user experience and i would love to discuss these improvements further or let know if you’re interested in contributing. So i can assign the task to you.

**Comment by CemWebDev** [comment]
Hey! I accidentally deleted my previous comment, so I'm reposting it here.

Hey! The design looks really clean and professional, especially the readability of the text and the headline is quite eye-catching. I have a few suggestions that could enhance the user experience:

- You might want to make the "Log in" button in the top menu a bit more prominent. For example, increasing the contrast or slightly enlarging the text size could help it stand out more.
- Adding a subtle opacity layer over the background image might make the text even easier to read.

If you'd like to discuss these improvements or collaborate, I'm happy to help.

**Comment by CemWebDev** [comment]
@yazdanhaider  I may not be able to look into today, but I'd love to check it out if possible. Hopefully, I can contribute when I have more time!

**Comment by yazdanhaider** [comment]
No problem at all @CemWebDev take your time whenever you are ready to check it out, feel free to contribute.

**Comment by Arshadkh123** [comment]
Hey @yazdanhaider I am eager to work with you on this issue. Even I thought your design looked clean and professional, especially the readability of the text, and the headline is quite eye-catching. I want to be with you. Can you assign this issue to me?

**Comment by yazdanhaider** [comment]
> Hey @yazdanhaider I am eager to work with you on this issue. Even I thought your design looked clean and professional, especially the readability of the text, and the headline is quite eye-catching. I want to be with you. Can you assign this issue to me?

Great!!! Go ahead @Arshadkh123 

Happy Contributing!!

**Comment by SaidSafwan** [comment]
Hey @yazdanhaider would like to contribute to this issue.

**Comment by yazdanhaider** [comment]
> Hey @yazdanhaider would like to contribute to this issue.

Heyyy @SaidSafwan Already i assigned the issue to @Arshadkh123 you sould look into that. Also i haven't asked to just add the image on the homepage!! Before committing to any repo please make sure that what changes have been asked for!!!

**Comment by yazdanhaider** [comment]
Heyyy @Arshadkh123, this message is regarding the UI of the Homepage. I have enhanced and modified the User Interface of the application. Let me know what additional changes you can make to further improve the updated UI. So accordingly i will assign you the issue!!!

**Comment by Arshadkh123** [comment]
heyy @yazdanhaider yes I am looking to it. I will inform you by tomorrow what to do it.

**Comment by yazdanhaider** [comment]
> heyy @yazdanhaider yes I am looking to it. I will inform you by tomorrow what to do it.

Sure as of now i’m closing this issue for now, but feel free to create a new one if there’s something else you’d like to work on.
