### ISSUE TITLE
Redirecting issue

### ISSUE THREAD

**Issue by mayank-0789** [yazdanhaider/Hospital-Management#21]
On clicking upon the logo of HMS from any section on the website it is not redirecting directly to the home page
#screenshot
<img width="1470" alt="Screenshot 2024-10-15 at 5 25 43 PM" src="https://github.com/user-attachments/assets/b853c46c-affa-42f7-b704-04217dac6903">

**Comment by mayank-0789** [comment]
Hey @yazdanhaider please assign this issue to me

**Comment by yazdanhaider** [comment]
Move Ahead @mayank-0789 

Happy Contributing!!!🔁
