### ISSUE TITLE
Enhance the styles and responsiveness of the home screen of the application

### ISSUE THREAD

**Issue by dharshini2022** [yazdanhaider/Hospital-Management#25]
**PROBLEM**
The home screen is underutilized with excessive empty space.
![Screenshot 2024-10-15 200113](https://github.com/user-attachments/assets/c38753a0-793f-4285-84fb-d3d7eee9d97e)

**Proposed Improvements**
- Apply efficient styles to optimize home screen styling.
- Build the layout with a mobile-first approach, ensuring that the content scales well from smaller devices to larger ones.

I would like to work on this feature. Please assign this issue to me under Hacktoberfest

**Comment by yazdanhaider** [comment]
Heyyyy... @dharshini2022 I’ve rechecked the homepage and didn’t notice any excessive empty space. The layout is designed to be fully responsive across different screen sizes. Could you please recheck the application and let me know if you still see the issue?
