### ISSUE TITLE
Enhancing the Doctor card

### ISSUE THREAD

**Issue by Pujan-sarkar** [yazdanhaider/Hospital-Management#28]
1. *Add Doctor Images*:
   - Including a section for doctor profile images at the top of each card. You can use placeholder images or actual doctor photos.

2. *Sliding View (Carousel)*:
   - Implementing a sliding carousel component, allowing users to swipe through the doctor cards horizontally. This can be done using libraries like react-slick or Swiper.js for a smooth and responsive experience.

3. *Doctor Rating*:
   - Adding a rating system with stars (⭐) or a numerical rating out of 5, below the doctor's name or specialty. Libraries like react-star-ratings can simplify this.

4. *Professional Card Design*:
   - Improving the card layout by adding subtle shadows, rounded corners, and a gradient or background color to make the design look more professional.
   - Using icons for specialties and patient counts to make the information more visually appealing.
   - Updating the font styles and sizes to maintain readability while enhancing aesthetics.
   
5. *Additional Styling Enhancements*:
   - Using contrasting colors for the "View Details" button and add a hover effect to make it interactive.
   - Adding padding and spacing for a cleaner, well-spaced layout.

**Comment by yazdanhaider** [comment]
Heyyyy @Pujan-sarkar  Already the doctor card is contributed by other person you checkout the frontend. Also if you can improve by adding some features like improve the UI of the card, sliding view, and ratings feel free to do it.

Move ahead also i assigning you the task. Best of luck!!

Here is current result!

# Screenshot
<img width="707" alt="Screenshot 2024-10-16 at 12 10 54 AM" src="https://github.com/user-attachments/assets/2cefdc16-7f43-4cbb-ba1e-240d62e4c110">

**Comment by Pujan-sarkar** [comment]
@yazdanhaider okay then let me see the ui, I will try to enhance it
