### ISSUE TITLE
Mitigate to ReactjJS

### ISSUE THREAD

**Issue by anirudh-why** [yazdanhaider/Hospital-Management#3]
Would like to mitigate this application to react js and improving the UI .

**Comment by yazdanhaider** [comment]
> Would like to mitigate this application to react js and improving the UI .

Just a heads-up, @anirudh-why is already working on the migration to ReactJS. But if you’re interested, I’d love for you to contribute to some other features. Let me know if you’re up for it! 😊

**Comment by archita-2810** [comment]
@yazdanhaider i'd like to work on other features, let me know so that i can start working on it.

**Comment by yazdanhaider** [comment]
> @yazdanhaider i'd like to work on other features, let me know so that i can start working on it.

Heyyyy @archita-2810 , please go through the project and the CONTRIBUTING guidelines. Let me know which features you’d like to work on.🙌🏻
