### ISSUE TITLE
Issue: Responsiveness and Misalignment in Patients Section

### ISSUE THREAD

**Issue by Krishna3451** [yazdanhaider/Hospital-Management#30]
## Description
In the "Patients" section of the Hospital Management System (HMS) interface, there are responsiveness and alignment issues when viewed on mobile or smaller screens. The table content does not align correctly, and the layout appears cluttered, causing a poor user experience on mobile devices.

## Steps to Reproduce
1. Open the Hospital Management System interface on a mobile device or resize the browser to a narrow width.
2. Navigate to the "Patients" section to view the list of added patients.

## Observed Behavior
- The columns and rows in the "Patients List" table do not align properly.
- Some text, like the "Delete" option, appears misaligned.
- The table content is difficult to read and does not adjust to fit the screen size properly.

## Expected Behavior
- The "Patients List" table should be responsive and align properly on mobile and smaller screens.
- All elements, including text and action buttons, should be displayed clearly and adjust based on screen size.

## Screenshot
![image](https://github.com/user-attachments/assets/e88d3e2f-c552-45b1-b46b-b39aef058993)

## Suggested Solution
- Implement CSS media queries to make the table responsive on smaller screens.
- Adjust padding, margin, and text alignment within table cells to ensure all elements align correctly.
- Test the "Patients" section on various screen sizes to ensure consistent behavior.

**Comment by Krishna3451** [comment]
@yazdanhaider I would like to work on this issue.

**Comment by yazdanhaider** [comment]
Great @Krishna3451. Go ahead and implement it. Also, make sure to display the patient list using a dropdown method. If you have any other implementation ideas feel free to go ahead with them.

I am assigning you this issue!! Happy Contributing🔁

**Comment by yazdanhaider** [comment]
Heyyy @Krishna3451, I’ve already fixed the responsiveness of the application! If you’re interested in contributing to any other parts, just let me know. Also i’m closing this issue for now, but feel free to create a new one if there’s something else you’d like to work on.👍🏻
