### ISSUE TITLE
Add Social Media Icons to the footer

### ISSUE THREAD

**Issue by pranavsuriya-sr** [yazdanhaider/Hospital-Management#39]
Add social media icons to the footer for an enhanced footer. Please assign this issue to me.

**Comment by nancy-gupta123** [comment]
Hello! I'd like to work on this issue. Could you please assign it to me?

**Comment by Harithaa2004** [comment]
hi could you assign this issue to me, i have already worked on a similar issue before 
![Screenshot 2024-10-16 121832](https://github.com/user-attachments/assets/592c9e31-6fdf-4c21-9a67-597aed34e8fe)
I have updated the footer to enhance the overall user experience. The changes include:
1.Adding social media icons for Facebook, Twitter, and Instagram.
2Including essential links such as Home, Products, About, Contact, and Privacy Policy for better navigation.
3.Ensuring the footer is responsive across all devices, maintaining a consistent design and functionality.

**Comment by yazdanhaider** [comment]
> Add social media icons to the footer for an enhanced footer. Please assign this issue to me.

Hey @pranavsuriya-sr , could you please provide a screenshot for reference showing the changes you plan to make in the footer?

**Comment by yazdanhaider** [comment]
> /assign

Heyyy @rohitja26 could you please provide a screenshot for the changes you have planned.

**Comment by yazdanhaider** [comment]
> I have updated the footer to enhance the overall user experience. The changes include:
> 1.Adding social media icons for Facebook, Twitter, and Instagram.
> 2Including essential links such as Home, Products, About, Contact for better navigation.
> 3.Ensuring the footer is responsive across all devices, maintaining a consistent design and functionality.

Heyyy @Harithaa2004 I appreciate the effort, but I didn’t quite like the design. Could you please make some changes and provide a screenshot for reference? I’d like to see something different that aligns more with the overall style of the site.

**Comment by rohitja26** [comment]
Heyy @yazdanhaider  I am thinking about to make the social media icons like the image provided below. I would also like if you provide how you to arrange the icons I will try to make them accordingly

![image](https://github.com/user-attachments/assets/9660f377-0139-4e43-ae9d-0046ab87a2fb)

**Comment by rohitja26** [comment]
Heyy @yazdanhaider  please reply ASAP so that I can start working on this

**Comment by yazdanhaider** [comment]
> Heyy @yazdanhaider please reply ASAP so that I can start working on this

Heyyy @rohitja26 I am attaching you the footer design for reference....If you could work on this then go ahead. I will assign you the issue!!

![image](https://github.com/user-attachments/assets/3760acff-4319-4953-b0e3-1613fab9064e)

**Comment by rohitja26** [comment]
okk I can do this please assign this to me

**Comment by yazdanhaider** [comment]
> @yazdanhaider okk I can do this please assign this to me

Go ahead!! @rohitja26 I am assigning you the task!!

Happy Contributing!!

**Comment by rohitja26** [comment]
@yazdanhaider  I have came with the solution below please provide feedback for improvements 
![Screenshot 2024-10-16 175141](https://github.com/user-attachments/assets/ac93c4c1-d7ff-4de0-a1a7-39e389bce759)

**Comment by yazdanhaider** [comment]
Great job @rohitja26 However I noticed that the logos are not centered properly. Could you please adjust their alignment to ensure they are centered within the footer.
<img width="823" alt="Screenshot 2024-10-16 at 6 01 29 PM" src="https://github.com/user-attachments/assets/f91003a3-7fd9-4cba-aba2-afd9aef2dfa1">

**Comment by rohitja26** [comment]
@yazdanhaider  okk Updated some changes and came to this solution hope you will like 



![Screenshot 2024-10-16 181819](https://github.com/user-attachments/assets/da09e167-6d32-4473-8626-f38de0c43281)

**Comment by rohitja26** [comment]
@yazdanhaider  I think you have liked this should I do a pull request ??

**Comment by yazdanhaider** [comment]
> @yazdanhaider I think you have liked this should I do a pull request ??

Yes, I really liked this! Please go ahead and create a pull request!
