### ISSUE TITLE
Add document title and favicon

### ISSUE THREAD

**Issue by ashish-um** [yazdanhaider/Hospital-Management#40]
I'll create a favicon logo for the website and modify the document title accordingly.

Hey @yazdanhaider  Please assign this task to me so that I can start working on it.
If there is any preference from your side, please tell me.
And also don't forget to add Labels on this for _**Hactoberfest**_

**Comment by yazdanhaider** [comment]
Heyyy @ashish-um, as of now, I don’t require the favicon logo. I appreciate your interest, though! If needed later, I’ll definitely reach out.

**Comment by ashish-um** [comment]
no problem, closing the issue as of now
