### ISSUE TITLE
Form validation is not available in booking appointment.

### ISSUE THREAD

**Issue by PrasuHirapara** [yazdanhaider/Hospital-Management#43]
@yazdanhaider previously i had validated form before submission. But due to some new changes it is not available now. I am doing **form validation** as it is crucial for valid data.
I will use it to **not allow user to have only numbers** in user section.
Also, user **can not book appointment on day which is gone already**. i will fix this too.
![image](https://github.com/user-attachments/assets/b80b5a86-d31c-4e84-a033-202073cf516d)

**Comment by yazdanhaider** [comment]
Great observation @PrasuHirapara,  It’s important to maintain form validation for data integrity. Please go ahead with implementing the changes including restricting numerical-only usernames and preventing appointment bookings for past dates. Thank you for addressing these crucial issues!

I am assigning you this issue. Happy contributing!!👍🏻

**Comment by PrasuHirapara** [comment]
Thank You.

**Comment by yazdanhaider** [comment]
Heyyy @PrasuHirapara, I noticed the same issue occurring when adding a new patient. Please address this as well. Thank you!

**Comment by PrasuHirapara** [comment]
@yazdanhaider yaa sure i would look after that and push new changes in few minutes.

**Comment by yazdanhaider** [comment]
> @yazdanhaider yaa sure i would look after that and push new changes in few minutes.

Sure!! Go ahead.

**Comment by PrasuHirapara** [comment]
@yazdanhaider i have created pull request. Kindly check and merge it

**Comment by yazdanhaider** [comment]
Thank you @PrasuHirapara for your contribution!!!

**Comment by PrasuHirapara** [comment]
@yazdanhaider your welcome
