### ISSUE TITLE
Specifying whether user is patient or doctor in sign up page.

### ISSUE THREAD

**Issue by PrasuHirapara** [yazdanhaider/Hospital-Management#48]
@yazdanhaider Specifying **whether user is patient or doctor in sign up page** is import to classify and differentiate each user and fetch data according. We just need to add selection tab to let user select between doctor and patient. 
My approach: **Get it via selection in sign up form** and **store it in database.**

![image](https://github.com/user-attachments/assets/aa42abf6-bd48-4576-959d-7d08cc9481c7)

**Comment by PrasuHirapara** [comment]
@yazdanhaider kindly assign it to me, I will solve this issue very soon.

**Comment by PrasuHirapara** [comment]
@yazdanhaider guide me. Should i do it or work on adding other features.

**Comment by yazdanhaider** [comment]
@PrasuHirapara, You’re absolutely right! Adding a selection tab in the sign-up form to classify users as either doctors or patients is a great approach for differentiation. Additionally i am thinking of also consider implementing a verification step for doctors to ensure authenticity to maintain the integrity of the platform.

**Comment by PrasuHirapara** [comment]
@yazdanhaider yes, validating doctors are crucial. We can do it via accessing pdf of proof uploaded via doctor. 
If user is doctor then form will contain section to add proof that.

**Comment by PrasuHirapara** [comment]
@yazdanhaider i have requested for merge. Please verify and accept.
