### ISSUE TITLE
Implement Signin and Signup of the patient.

### ISSUE THREAD

**Issue by sujal1256** [yazdanhaider/Hospital-Management#53]
I can send the form the data while adding new patients to the backend and data will be saved in the database.
I will require
using dotenv library to fix CORS policy
Send the data to backend
Data to be saved in database

**Comment by sujal1256** [comment]
@yazdanhaider Please assign this task to me I have started working on this issue

**Comment by yazdanhaider** [comment]
Go ahead with the implementation! @sujal1256, Also do implement the same for **booking appointments.** And maake sure to use the dotenv library for managing environment variables and fixing the CORS policy. Once you send the form data to the backend ensure it gets saved correctly in the database.

**Comment by sujal1256** [comment]
Ok I will take care of that

I am done with patients registration, will do patient login and delete patients, I will do these things in this PR and do the booking appointment in the next 
If you are ok with that

**Comment by yazdanhaider** [comment]
Yess issue no. #48 just fixed. There is now different sign up options for both patient and doctors. You can now checkout the site!!!
