### ISSUE TITLE
Implement a Backend

### ISSUE THREAD

**Issue by RakinduM** [yazdanhaider/Hospital-Management#6]
I would like to implement the Backend for the website using Node js, express js and mongo db as the database. After implementing the backend,  anyone can contribute to it to improve. Consider and assign me to work on it.

**Comment by yazdanhaider** [comment]
Sure @RakinduM, that sounds great! I’ll assign you to the backend implementation task to you..... And looking forward to your contributions. Let me know if you need any help along the way!

Best of luck🤞

**Comment by shangesh-tech** [comment]
Yes , i also help in this backend implementation , can we join together and complete this work..
@yazdanhaider 
@RakinduM

**Comment by PrasuHirapara** [comment]
@RakinduM @yazdanhaider have you started working on backend set up ? I would also like to contribute to backend. I am good at it and have strong knowledge on it. You may check my project on the same at https://github.com/PrasuHirapara/StockTracker-Hub/tree/main/backend

**Comment by RakinduM** [comment]
I implement the Backend and made a pull request @yazdanhaider .Yea  There're more we can add to Backend. @PrasuHirapara @shangesh-tech
