### ISSUE TITLE
Add Additional Doctor Specializations to the Doctor Page

### ISSUE THREAD

**Issue by Devmangrani** [yazdanhaider/Hospital-Management#69]
I would like to contribute by adding doctor profiles for the following specializations that are currently missing from the Doctor page:

General practitioner
Anesthesiologist
Ophthalmologist
Psychiatrist
Gastroenterologist
Otolaryngologist
Radiologist
Dentist
Endocrinologist
Nephrologist
Pathologist
Surgeon
Geneticist
Hematologist

**Comment by Devmangrani** [comment]
Please Assign these Issues to me and add a Hacktoberfest label on it...

**Comment by yazdanhaider** [comment]
Go ahead @Devmangrani

Happy Contributing!!
