### ISSUE TITLE
Navbar Responsiveness Issue: Layout Breaks on Smaller Screens

### ISSUE THREAD

**Issue by Shreyhac** [yazdanhaider/Hospital-Management#7]
The top navbar of the Hospital Management System website is not responsive. When viewed on smaller screens, the navbar breaks and does not adjust properly.
<img width="379" alt="Screenshot 2024-10-15 at 00 53 29" src="https://github.com/user-attachments/assets/c823ef8b-89dd-4708-9ce2-003751d6eb69">

**Comment by yazdanhaider** [comment]
Heyyyy @Shreyhac, Thanks for pointing that out. Since our web application has been migrated to **React.js**, please review the project and let me know what contributions you’d like to make. We can then assign the relevant tasks accordingly.

**Comment by shangesh-tech** [comment]
can you assign this to me.. @yazdanhaider 

can convert this design to tailwindcss ,
if you want to check my designing work , here is some of my project link:-

https://fin-pay-six.vercel.app/

https://mern-food-frontend-6ywd.onrender.com/


(This Mern stack project--> Full stack application)

**Comment by yazdanhaider** [comment]
Heyyy @shangesh-tech, please proceed with the task. Make sure to avoid using the same design from the two previous projects and come up with something new and creative. Best of luck! I’m assigning this task to you.” 🤞🏻

**Comment by shangesh-tech** [comment]
@yazdanhaider 

as i gothrought this project , i see here for responsive use Media query , can i change to tailwind css responsive system....

**Comment by yazdanhaider** [comment]
Go on @shangesh-tech.
