### ISSUE TITLE
Adding Sign Up Page in Admin Panel

### ISSUE THREAD

**Issue by Nayanika1402** [yazdanhaider/Hospital-Management#8]
If the person is new to the website he needs to first sign up create a account and then only the the log in option will be available in the admin panel.I want to add Sign up page for the website.
@yazdanhaider Kindly assign me the issue.

**Comment by shangesh-tech** [comment]
yes , Interesting work , i can do it ...
pls assign this work to me

**Comment by shangesh-tech** [comment]
@yazdanhaider

**Comment by yazdanhaider** [comment]
> yes , Interesting work , i can do it ... pls assign this work to me

As @Nayanika1402 was the first to raise this issue, I’m assigning the task to her. However you’re welcome to contribute in other areas.
