### ISSUE TITLE
[chore] : Update About Us Tab to Match Homepage Description

### ISSUE THREAD

**Issue by CynthiaWahome** [yazdanhaider/Hospital-Management#83]
Hi @yazdanhaider 
The About Us section write up in the homepage is different from the one in the About Us tab. See screenshot below.

**Homepage**
![image](https://github.com/user-attachments/assets/9db4f745-3813-481f-acb9-f3fa477d55a4)
**About Us Tab**
![image](https://github.com/user-attachments/assets/bbd928ca-7bc3-4e5f-aacd-1f2bfe6e052a)

Could I modify the write up in the in About Us tab to read...

> 
> **About Us**
> **Health Nest** is an advanced Hospital Management System (HMS) created to transform the way healthcare facilities operate and deliver patient care. Our cutting-edge platform simplifies healthcare workflows, enhances efficiency, and reduces errors, leading to better patient outcomes.
> 
> Our mission is to empower healthcare providers with innovative technology that streamlines operations and supports superior patient care. By integrating the expertise of healthcare professionals and software engineers, we are dedicated to developing solutions that adapt to the ever-changing needs of modern healthcare.
> 
> At **Health Nest,** we are committed to shaping the future of healthcare management by providing intuitive, reliable, and impactful technology solutions.

Let me know. This will be for a Hacktoberfest submission.
Thanks!

**Comment by yazdanhaider** [comment]
Hey @CynthiaWahome Already this issue have been fixed #82, the "About Us" page UI has been improved. You can check it out. Also if you want to contribute to some other feature let me know.

**Comment by CynthiaWahome** [comment]
@yazdanhaider Instead of referring to the company as HMS could we call it Health Nest in the About Us section?

This
**Health Nest is an advanced Hospital Management System (HMS)** designed to streamline healthcare operations and improve patient care.

Instead of this
**Hospital Management System (HMS) i**s a cutting-edge solution designed to streamline healthcare operations and improve patient care.

Let me know.
Thanks.
