### ISSUE TITLE
[docs] : Add Setup Instructions for Frontend and Backend in README

### ISSUE THREAD

**Issue by CynthiaWahome** [yazdanhaider/Hospital-Management#84]
Hi @yazdanhaider, 
The current README file for the HealthHub project lacks detailed setup instructions for both the frontend and backend. To enhance clarity and assist new developers in getting started, we should include the following information:

1. **Frontend Setup Instructions**:
   - Navigate to the `frontend` directory.
   - Install dependencies using `npm i`.
   - Run the development server with `npm run dev`.

2. **Backend Setup Instructions**:
   - Navigate to the `backend` directory.
   - Populate the `.env` file with necessary environment variables, including:
     ```
     DB_URL=
     PORT=
     JWT_SECRET=
     NODE_ENV=development
     ```
   - Install backend dependencies using `npm i`.
   - Run the development server with `npm run dev`.

Please assign this for me as an entry of Hacktoberfest.
Thanks!

**Comment by yazdanhaider** [comment]
As of now there's no need to change the `Readme.md`. If you want to make any other changes let me know.
