### ISSUE TITLE
Adding a Review Section

### ISSUE THREAD

**Issue by SrishtiChamoli** [yazdanhaider/Hospital-Management#91]
To enhance the user experience on the website, we can implement a review and rating pop-up that will appear after 15 seconds of the user being on the homepage. This approach strikes a balance between gathering valuable feedback and not overwhelming users immediately upon entering the site. The delay allows users to engage with the content first, ensuring their interactions are meaningful before prompting them for feedback. 

The pop-up will invite users to rate their experience with a star-based rating system and provide written comments if they choose. This addition is aimed at improving user satisfaction, encouraging engagement, and collecting insights to further optimize the site’s performance and design.

**Comment by yazdanhaider** [comment]
Could you please provide some references for this feature? It would help me decide more easily.

**Comment by SrishtiChamoli** [comment]
A rating cum review section will pop up on the screen after 15 seconds of being on the website..It will increase user engagement and their experience.![image](https://github.com/user-attachments/assets/296caf7e-1bdb-4cc1-9169-bac13201394c)


A comment box will also be included along with the star rating..It will roughly look like the above image provided.

**Comment by yazdanhaider** [comment]
That sounds like a great idea! Go ahead @SrishtiChamoli!

Assigning you the task. Happy Contributing!!
