### ISSUE TITLE
Improve Terms of Service Section for Better UI Performance

### ISSUE THREAD

**Issue by ansiace** [yazdanhaider/Hospital-Management#92]
I have identified a need for enhancement in the **Terms of Service** section. Currently, the section lacks sufficient detail and could be improved for better user experience and clarity.

#### Proposed Changes:
- Add additional points to the **Terms of Service** section to provide more clarity and information.
- Ensure that the section layout is optimized for **UI performance**.

![{EDBE52CD-5BE5-4394-B4BF-E29C4A814ABC}](https://github.com/user-attachments/assets/c976c2bc-cfab-4c49-821d-9c1d66fdaade)

**Comment by yazdanhaider** [comment]
Heyyyy @ansiace, As of now I don’t have any plans to make changes in TOS. If you want to add a feature or fix a bug, please let me know.

**Comment by ansiace** [comment]
I want to add some more points on TOS for the Hospital Management.

**Comment by yazdanhaider** [comment]
> I want to add some more points on TOS for the Hospital Management.

As of now it's not required!!

**Comment by ansiace** [comment]
Ok Fine
