### ISSUE TITLE
There is an unexpected error occurring while navigating to patients page

### ISSUE THREAD

**Issue by Kruthik111** [yazdanhaider/Hospital-Management#97]
![{1F9F50FC-895C-4E44-B659-99FEE4297796}](https://github.com/user-attachments/assets/5e1ad549-a23d-4865-81f4-f400bd7804d3)
 There is no problem when ran locally, but in deployment only its occurring. I couldn't rectify it, someone can take up this issue.

**Comment by yazdanhaider** [comment]
Go ahead! Assigning you the issue.
